image: docker:latest

services:
  - docker:dind

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - build
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main

deploy:
  stage: deploy
  script:
    - ssh user@server "docker pull $CONTAINER_RELEASE_IMAGE && docker stop flask_app || true && docker rm flask_app || true && docker run -d --name flask_app -p 80:5000 $CONTAINER_RELEASE_IMAGE"
  only:
    - main